name: Deploy Urara to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set environment variable for static adapter
        run: echo "ADAPTER=static" >> $GITHUB_ENV

      - name: Install dependencies with legacy-peer-deps
        run: npm install --legacy-peer-deps

      - name: Build Urara site
        run: npm run build

      - name: Download build.tar from the repository
        run: wget https://github.com/rompelhd/bl4ckh4ck.github.io/raw/main/build.tar

      - name: Extract all files from build.tar except hello-world
        run: |
          mkdir temp_build
          tar --exclude='hello-world' -xvf build.tar -C temp_build

      - name: Copy extracted files to the build directory
        run: cp -r temp_build/* build/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
